### ISSUE TITLE
Question about convlstm.

### ISSUE THREAD

**Issue by aflyingnoob** [wangbo-zhao/WSVSOD#3]
Sorry to disturb you, I have a question about lstm which is used by your paper, the video frames are large, even some video contains 400+ frames, if we send all of them to lstm, it would induce memory overflow. Or you cut the 400+ frames to several parts and send them to lstm separately? Thanks.

**Comment by wangbo-zhao** [comment]
Yes. To the best of my knowledge, most methods for video usually cut the video to several parts, especially methods for video segmentation.
